---
# tasks file for googlechrome | Debian/Ubuntu Family

- name: Update repository cache and install gnupg2
  ansible.builtin.apt:
    name: gnupg2
    update_cache: true
  when: "ansible_os_family == 'Debian'"

- name: Debian/Ubuntu Family | Add gpg signing key for {{ googlechrome_app_name }}
  ansible.builtin.get_url:
    url: "{{ googlechrome_gpg_key }}"
    checksum: "{{ googlechrome_gpg_key_checksum }}"
    dest: /usr/share/keyrings/google.asc
    mode: '644'
  notify: Update apt cache to include the new repo

- name: Debian/Ubuntu Family | Adding repository {{ googlechrome_repo_debian }}
  ansible.builtin.apt_repository:
    repo: "{{ googlechrome_repo_debian }}"
    state: "{{ googlechrome_repo_desired_state }}"
    filename: "{{ googlechrome_repo_debian_filename }}"
    update_cache: yes

- name: Debian/Ubuntu Family | Installing {{ googlechrome_app_name }}
  ansible.builtin.apt:
    name: "{{ googlechrome_app_name }}"
    state: "{{ googlechrome_desired_state }}"
    force_apt_get: yes
    update_cache: yes
